### ISSUE TITLE
Method #fonts breaks the old pdf

### ISSUE THREAD

**Issue by paulslaby** [boazsegev/combine_pdf#111]
Just touching pdf.fonts and saving breaks the text.

This is the whole script, I use:
```
pdf = CombinePDF.load ARGV.shift
pdf.fonts
pdf.save "combined.pdf"
```
on this file: [PS_vizitka_konkretni_petr_vondra.pdf](https://github.com/boazsegev/combine_pdf/files/1070564/PS_vizitka_konkretni_petr_vondra.pdf)

Is it, what do you say as known limitation? I'd like to help you, but i need a little guidance ;-)

**Comment by boazsegev** [comment]
@paulslaby  - Nice catch! My tests didn't catch this.

It was a typo (a `=` instead of a `==`). I fixed it and I'll release a patched version in a bit 👍 

Thanks!

**Comment by boazsegev** [comment]
@paulslaby  - nice catch! 👍🏻

It was a typo (a `=` instead of a `==`).

I fixed it and I'll release a patch in a bit.

Thanks!

**Comment by paulslaby** [comment]
You are really quick when it comes to fix bugs. 👍  Thanks. 
I know, it is not this thread topic, but now it works like this: http://prntscr.com/fjjof9 The upper one is added by textbox method. I think boldness won't be difficult. 
Am I able to add kerning? I'd like the same quality as the old one and I wonder if it can be done this way

**Comment by boazsegev** [comment]
Thanks :-)

Fonts are super tricky... I left them alone after I got just enough features that allow me to hack known entities (PDFs I explore using CombinePDF manually before using their fonts)...

... maybe someone who knows more about fonts will write something and contribute, but I wouldn't hold my breath.

If this is a templet you can check in `irb`, than try using different fonts.

The "Bold" variation should be registered as a different font rather than a "style". Either that, or it would have a CMap where the same letter appears more than once, which I really doubt.

"Bold" is nothing more than a different glyph and PDF fonts are simple arrays of glyphs (limited to 255 keys, that's why PDFs don't support UTF-8).

How many fonts does the file list? maybe try a different one?

It's three in the morning here and I'm still working, so I can't test it out myself, but I do wish you tons of luck! keep me posted.

**Comment by paulslaby** [comment]
In the file there are three fonts:

    > pdf.pages.first[:Resources][:Font].values.map{|f| f[:referenced_object][:Subtype]} 
    => [:Type0, :TrueType, :TrueType] 

When I run `pdf.font`, there is only the first one. There is no ToUnicode key... Will investigate more...
