### ISSUE TITLE
Malforms PDF

### ISSUE THREAD

**Issue by erikaxel** [boazsegev/combine_pdf#124]
Hi,

First of all, thank you very much for an excellent gem. It has worked very good for us for some time now.

I came across a PDF that it malforms when trying to combine it. It cuts of the header of the PDF, and more importantly, many pdf readers are not able to read the new combined PDF. 

An easy way to see the "cutting" effect is by using your demo at http://combine-pdf-demo.herokuapp.com/. Just upload the PDF and then the header will be cut, and the PDF is not openable in Mac Preview. (it works in Chrome pdf preview however).

I will send you a link to the PDF in question directly. It is not supersecret, but would prefer it not to live at github for the rest of eternity.

**Comment by boazsegev** [comment]
Hi @erikaxel,

Thank you for opening and and exposing this issue.

I received the PDF and can confirm the issue, although I couldn't find the root cause as of yet.

I'll look it over and report back what I find.

Kindly,
   Bo.

P.S.

As indicated in the README, this project has a lower priority relative to my other projects (most them aren't published, but are far more relevant to my life these days). I hope to resolve the issue soon, but it might take a while since I don't have enough hours for everything right now.

Help would be appreciated.

**Comment by boazsegev** [comment]
Hi @erikaxel ,

Thank you again for opening this issue.

I just released a fix. You can test it out by installing version 1.0.7.

Please let me know if you need anything else.

Kindly,
  Bo.

**Comment by erikaxel** [comment]
Hi Bo,

Thank you very much for tracking down and fixing this issue. Especially when your time for this project is so limited. I can confirm that it works, very much appreciated.
