### ISSUE TITLE
Green boxes appear when combining PDFs

### ISSUE THREAD

**Issue by bedaronco** [boazsegev/combine_pdf#130]
When combining PDFs sometimes green boxes appear over content.  This seems to happen when there is overlapping elements.  For instance, there might be a text box over an image and for some reason it appears dark green after the combine.  I've also seen it when there is an empty box behind some text.  The empty box seems to turn dark green for some reason so I end up with black text on dark green.  It's very odd.

I don't know where the dark green color would be coming from.  I'm trying to get a PDF that I can share but it might take awhile to do that.  In the meantime, if there is any insight into where the green would come from that might be helpful in tracking this down.

**Comment by boazsegev** [comment]
Hi @bedaronco ,

Thank you for opening this issue.

Sadly I have no great insight as to where the green color might be coming from.

The only thing I can think of is a color space type clash (I'm not even sure if that's possible). For example, a mixup between RGB and BW / Grayscale or maybe CMYK might occur.

It's the only idea I have, even though I find it very unlikely and surprising, since each page should define it's own color space within it's content stream (I think the default is RGB) and the color choices in PDF define the color space along with the color (in pseudo PDF code a call to `1 1 1 rg` would choose white from the RGB space), allowing color spaces to change dynamically.

If you find an example PDF please send it my way, as I have nothing that can replicate this issue.

**Comment by bedaronco** [comment]
Ok, thanks. It's not the entire page that gets messed up.  It will just be a section of the page, typically as the background to a text box or some some weird looking masking applied to an image.

**Comment by boazsegev** [comment]
Could you check the PDF version indicated in `PDF.version`?

Versions before 1.4 don't support transparency. Saving the PDF the the wrong version number might cause issues (though that would be reader specific rather than file specific).

**Comment by bedaronco** [comment]
The version of the file being combined is 1.5 and the resulting combined document is also 1.5.  So it should be good.

I think it's processing files through ghostscript before combining that is causing the issue.  If I don't run ghostscript on the file then combine works fine.  If I run ghostscript I then see the green boxes.  With or without running ghostscript the file looks fine in pdf.js or Acrobat.  Very strange.  I run through ghostscript to help out with a lot of font issues that I was seeing when combining PDFs from different sources.

**Comment by react-rails** [comment]
Same issue in my application
After running Ghostcript on the PDF file, then combined pdf.
Dark green boxes appears on the PDF background.

**Comment by react-rails** [comment]
In my opinion, the transparent images in PDF become dark green background image when combining.

**Comment by react-rails** [comment]
Hi Bo
Thanks for your consideration.
1. Let me attach the example PDF here.
[green_background_issue.pdf](https://github.com/boazsegev/combine_pdf/files/1678506/green_background_issue.pdf)

2. Just I released that without running GhostScript this issue happened.

Best,
Zhang

**Comment by react-rails** [comment]
PS* attaching the result pdf by CombinePDF.
[combinepdf_green_background_issue.pdf](https://github.com/boazsegev/combine_pdf/files/1678516/combinepdf_green_background_issue.pdf)

**Comment by boazsegev** [comment]
@react-rails ,

Thank you for the example PDF.

I tried reproducing the issue... but I can't. I added page numbers and text to the page without an issue. I even overplayed the same page onto of itself without any green boxes.

Can you provide code that demonstrates how to replicate the issue?

 Thanks!

P.S.

What CombinePDF version are you running?

**Comment by react-rails** [comment]
Hi @boazsegev 
Here is the code and sample pdf again.
https://www.dropbox.com/s/ng5bnvbv9m4zina/combine-pdf-green-background-issue.zip?dl=0

combine_pdf gem version is 1.0.7.
I have tested with other versions but same issue.
Thanks for your help!

**Comment by boazsegev** [comment]
Thanks! I'll test again tomorrow and try to figure out where things go sideways.

**Comment by boazsegev** [comment]
@react-rails  P.S.

A shorter variation of the code (both for you and anyone wishing to help):

```ruby
pdf = CombinePDF.load("/Users/2be/Desktop/PDF issues/test.pdf");
area_page.orientation :landscape # forces the PDF to landscape using a rotation (if required)
pdf.save "3.pdf"
```

**Comment by react-rails** [comment]
Thanks @boazsegev 
You can ignore fixing orientation block for now.
Just opening and save become green background.

Thank you!

**Comment by react-rails** [comment]
Hi @boazsegev 
Do you have any update for me? Or any solution on my side?
Thanks

**Comment by boazsegev** [comment]
Hi @react-rails ,

Sadly I can't pin the issue down.

I've spent hours trying to figure out the differences between the PDF file data (I manually read through the PDF file data, which isn't possible for all the data because GhostScript compresses some of the data which makes it unreadable).

I did notice that if I open the test PDF in a different reader (I used my mac's Preview app) and save it in a different name (or add annotations), than CombinePDF will parse the saved file properly.

I also noticed missing white spaces in the test PDF (it doesn't properly mark data stream endings and it doesn't end names or strings with whitespace)... but the CombinePDF parser anticipates such non-conforming behavior and fixes these issues on the fly (I couldn't find anything that wasn't parsed correctly).

I'm at the verge of giving up. I still want to look into PDF resource "inheritance" and possible resource name conflicts, but my initial testing in that vain turned up dry (no issues to be found).

I have no idea how to solve this, so I'm giving it a rest for a few days in hope that a fresh look will expose more details and hints.

B.

**Comment by react-rails** [comment]
@boazsegev 
Thank you for updating me.

**Comment by boazsegev** [comment]
Hi @react-rails ,

I woke up in the middle of the night with a thought... that thought led to some code which led to a test which... I think (or hope)... led to the extermination of one nasty hidden bug.

It seems that there was an octal escaping error in the parser. The error would be undetected since the "mutation" effected the references as well as any named objects (so there weren't any negative side affects... except for color map corruption - and hardly any PDF authoring system uses color maps, so it wasn't clear at all).

Anyway, I just released an updated version which might fix the issue.

Please let me know if this works. 🙏🏻

B.

**Comment by react-rails** [comment]
Great! This works now! Perfect! 
Actually I have been struggling with this issue for weeks but could not find any solution.
I really appreciate your help.
Thank you
Zhang

**Comment by boazsegev** [comment]
Thank you too, Zhang!

Without your data and input, I might never have found the source of the issue. 🙏🏻👍🏻

**Comment by bedaronco** [comment]
Wow!  I can't believe someone else had this problem.  This is very exciting news.  I can't wait to try it out.
