### ISSUE TITLE
Question regarding large numbers of PDFs

### ISSUE THREAD

**Issue by uidzip** [boazsegev/combine_pdf#138]
It would seem from the API that combine_pdf operates entirely in memory; that is, the combined PDF must fit in memory all at once.

If this is true, how much work would it be to have a mode of operation whereby the combined PDF is written out when a PDF is added to it, and then appended when the next one is written?  Thus it would be possible to stream a very large number of PDFs into a single combined PDF, even larger than memory would allow.

I would be willing to contribute to this since it is pure ruby and does not have a C library like facil.io :). (I previously helped identify an issue with the web socket handling).

**Comment by boazsegev** [comment]
Hi @uidzip ,

Thank you very much for opening this issue and for your kind offer (as well as your help in the past) :-)

Yes, the CombinePDF datastore and it's API run completely in-memory. The whole approach parses the PDF and breaks it into editable Ruby objects (Hash tables, Arrays, etc').

The PDF format was designed to be very similar to PostScript (i.e., `arg1 arg2 func`), so parsing the PDF data as if it was a programming language structure made sense to me.

In order to change this approach and move the datastore into a tmp file...

Well, I don't know, it seems like a huge amount of work and it would depend on the chosen design. I really wouldn't be sure where to start.

I guess it would be possible to save all the pages to a temporary file(s) and keep the core PDF structure in memory (so it could be easily updated as pages are added). However, this might prevent pages from being edited (page numbering, text boxes and all these operations require changes to the page data, which changes the length of data in the the file and requires everything in the file to move).

Another option is to never save the parsed data. A first pass parsing for each PDF file would just collect important general data (number of pages, font name, etc') and editing would be actionless (simply saving the requested edit to a dataset without performing it). This way, when `save` or `render` are called the parsing and actions can be performed directly to the output.

On the other hand, both of these approaches would require a lot of work. You might be better off starting from scratch and using CombinePDF for parts rather than trying to move CombinePDF's datastore to a file.
