### ISSUE TITLE
combinePDF number_pages method not wok

### ISSUE THREAD

**Issue by roma86** [boazsegev/combine_pdf#14]
First of all thank you very match for this great library. Can not figure out why so small amount of stars. 

One issue i have. 

```rb
@pdf_combiner = CombinePDF.new
#loop start
dfp = CombinePDF.new(pdf_path)
@pdf_combiner << pdf
#loop end

@pdf_combiner.number_pages
@pdf_combiner.save book_pdf_path if @pdf_combiner

#done!

```

This code works. All pages merged and final pdf stored in file system. 
Expect pages numbering.
Can non figure out what the problem is.

**Comment by boazsegev** [comment]
Hi Roma,

I'm happy you are enjoying the project and I thank you for opening this issue and helping make the combine_pdf gem even better.

I couldn't seem to reproduce the exact same issue on my system, although I did notice that in some cases, some pdf pages wouldn't show the text added to them due to the structure of the page's Resources dictionary (part of the PDF format).

**I just released an updated version**, fixing the issue related to the Resources dictionary, but I would love to investigate this further just in case it doesn't resolve the issue you encountered.

_Would you mind testing the updated version (version 0.1.17) to see that if the issue was resolved?_

**In case the issue persists**:

I was wondering if you could give me more details that might help me reproduce the issue or identify it's cause.

Could you please tell me what ruby interpreter you are running (I'm running the standard MRI, but many people use JRuby or Rubinius)? Also, what version of ruby are you running (I'm running the 2.2.0 version, but the gem should work on anything above 1.9.0)?

Since the issue is only with page numbering, could you check what happens when you change the default numbering settings? Maybe try changing the font size or positioning...?

for example, try: `@pdf_combiner.number_pages font_size: 120`

This could help narrow down the causes. It could be that the size, relative to the page size, is too small.

Also, would you mind trying to add sample text? The numbering system is based on the CombinePDF::Page_Methods#textbox method. If this method works, it will help us narrow down the cause even further.

Please check if this line of code works:

`@pdf_combiner.textbox "Hi!", box_color:[0.3,0,0.3], font_color: [1,1,1]`

Again, thank you for opening this issue,
   Bo.

**Comment by roma86** [comment]
Hi, Bo!
Thank you for quick answer and help. 
Nothing wrong with library, but usage. 
I just include wrong version in my gemfile ![because of this versions representation](https://api.monosnap.com/rpc/file/download?id=vqKhCEyZAiJ0ZG9Eqo0RhJsZTNKQdP)

when i use this

```ruby
#Gemfile
gem 'combine_pdf', '~> 0.1.17'

#Usage class
gem 'combine_pdf', '=0.1.17'
require 'combine_pdf'

#work with lib...

```
page numbering works fine with default options. 

Tank you for your work one more time.
