### ISSUE TITLE
Unknown PDF parsing error - malformed PDF file?

### ISSUE THREAD

**Issue by solasdev** [boazsegev/combine_pdf#140]
When I run the following:
CombinePDF.parse Net::HTTP.get_response(URI.parse('https://s3.amazonaws.com/primo-files/BXCLawHERyydAiutimWT%2BQuarterlyEPA.pdf')).body

i get...
Warning: parser advancing for unknown reason. Potential data-loss.
Warning: parser advancing for unknown reason. Potential data-loss.
CombinePDF::ParsingError: Unknown PDF parsing error - malformed PDF file?

Any ideas? I was combining this same file only a couple of months back with same code, not sure what's changed to break it.

Thanks

**Comment by solasdev** [comment]
I thought maybe like in another thread the url was using unsupported AESv2 encryption however if I download the file and try parse it I get the same error.

**Comment by boazsegev** [comment]
@solasdev ,

Thank you very much for discovering and opening this issue! 🙏🏻🙏🏻🙏🏻👍🏻

The file in the linked was a great help to tracking down the issue and authoring a solution.

It seems that the PDF used a fragmented XREF table, which CombinePDF's new XREF parsing logic (introduced in version 1.0.10 to resolve bug #131) didn't expect.

I updated the logic, tested it and release version 1.0.12 which should solve the issue. Please update and enjoy the fix.

Thanks again! Please let me know if there are any further issues.

Kindly,
B.

**Comment by dangerous** [comment]
I have the same issue, introduced by version 1.0.12 (works in 1.0.11).  @boazsegev I can send you the PDF that triggers the problem but am unable to share it publicly here.

**Comment by boazsegev** [comment]
@dangerous ,

Didn't the CombinePDF update (version 1.0.13) fix the issue?

Maybe it's something slightly different. If the issue persists, please send me a copy of the PDF to my email (I won't post it online)...?

Kindly,
  Bo.

**Comment by dangerous** [comment]
no it's still broken in 1.0.13

email sent

**Comment by boazsegev** [comment]
@dangerous , Thanks! 🙏🏻 

I'll see what I can do. I hope I have time later this week or during the weekend.

**Comment by boazsegev** [comment]
@dangerous ,

I released a fix (version 1.0.14). I hope it works for you.

The issue was caused by a surprisingly malformed EOL marker (`"\r"` instead or `"\r\n"`) in the XRef table. I was surprised because Adobe PDFs are usually better behaved than others.

There was just one of those, but it was enough to throw the parser off.

The parser will now be more flexible around such errors in Xref tables.

Thank you for your comment and for exposing the issue 🙏🏻🙏🏻🙏🏻

Kindly,
   Bo.

**Comment by kirillian** [comment]
@boazsegev I have what appears to be another edge case for CombinePDF's parser. I am happy to open another issue if that is preferable, but the issue I have appears to be closely related - at least the error message is the same and I wanted to post here first in case it stayed relevant. Note that we have one extra line in the output that differs from the original poster. Unsure if that means something to you:
```
Warning: parser advancing for unknown reason. Potential data-loss.
Warning: parser advancing for unknown reason. Potential data-loss.
... (there are a lot of these) ...
Warning: parser advancing for unknown reason. Potential data-loss.
Stream not attached to dictionary!
```

I would be happy to send you a PDF as it appears that is the way of things. We are encountering this on versions 1.0.11 through 1.0.15 though we just bumped to 1.0.14 recently per other similar issues after having found this thread previously. The output from versions 1.0.11 and 1.0.12 were slightly different, but that appeared to just be changes to the logging. Happy to provide those if you would like.

**Comment by boazsegev** [comment]
Hi @kirillian ,

Thank you for exposing a possible issue with CombinePDF. I hope we can sole this quickly.

By design, the log messages are similar in most cases where the parser fails. The reason being that the parser is mostly unaware as to the cause of the failure, so it can't report it properly.

Could you open a new issue and send me a sample PDF?

Thanks!
    Bo.
