### ISSUE TITLE
CombinePDF throwing unclear exception on malformed PDFs

### ISSUE THREAD

**Issue by kirillian** [boazsegev/combine_pdf#147]
@boazsegev I have what appears to be another edge case for CombinePDF's parser. We're getting the malformed PDF as previously described when i posted here: #140.

Warning: parser advancing for unknown reason. Potential data-loss.
Warning: parser advancing for unknown reason. Potential data-loss.
... (there are a lot of these) ...
Warning: parser advancing for unknown reason. Potential data-loss.
Stream not attached to dictionary!
I sent you the PDF as requested. We are encountering this on versions 1.0.11 through 1.0.15 though we just bumped to 1.0.14 recently per other similar issues after having found this thread previously. The output from versions 1.0.11 and 1.0.12 were slightly different, but that appeared to just be changes to the logging. Happy to provide those if you would like.

**Comment by boazsegev** [comment]
Hi @kirillian ,

Thank you for opening this issue and for sending me the PDF in question.

I think I found the issue... Sadly, I don't see a way to fix the issue without breaking the error reporting system or re-writing the parser from the ground up.

The PDF is malformed and I wouldn't even trust that it would be displayed the same on every PDF reader (although, theoretically it should).

I appears large sections of the file were re-written and a haphazard manner, leaving junk data and malformed content in the middle of the file it (it looks like it was iText, but maybe I'm wrong).

For example, in the middle of the file, one XRef table was overwriting another, leaving the original XRef table starting in the middle, with no keyword to identify itself, as you can see on the line after `%%EOF`:

```ps
xref
0 358
0000000000 65535 f 
0000123330 00000 n 
% ...
startxref
123425
%%EOF
0 n 
0000056196 00000 n 
0000057726 00000 n 
% ... 
```

I may be wrong in my assessment, but it appears even worse than that... The same object identifiers (i.e., `1 0 obj`) have been re-used to mark different objects, without change to their revision number (the second of the two numbers).

Most PDF readers probably don't encounter these issues because they would ignore most sections of the file.

This is because PDFs are usually read backwards (allowing them to display a single page or two without reading the rest) and a lot of the data in this PDF is probably never processed (nothing links to it)... but different readers might behave differently.

Opening the PDF in macOS and reserving it seems to fix the PDF.

I'm still wondering if there's anything I could do. If you have any ideas, please feel free to comment.

Kindly,
   Bo.

**Comment by kirillian** [comment]
First of all, I'm super appreciative for your time. We'll be rejecting PDFs that fail in this way it seems. We accept PDFs from people that we have little control over, so we'll have to keep digging to find out how this occurred (we have yet to receive a response on where this PDF was created) so we can add it to our guidelines as a "don't use this". I'm happy to close this issue if it's a thing you feel like you can't fix or just can't reasonably support at this time.
