### ISSUE TITLE
Pages counter pdf

### ISSUE THREAD

**Issue by curiosport** [boazsegev/combine_pdf#149]
Hello.

What part of your code counts pages in a pdf? I would like to be able to use that code without having to import the gem into my module.

Thank you.

**Comment by boazsegev** [comment]
Hi @curiosport ,

I'm think my answer might disappoint you, because the page "counting" code only works after the PDF was parsed and deconstructed into Ruby objects.

In practice, [CombinePDF collects all the Ruby objects that represent valid (viewable) PDF pages and returning them as an Array](https://github.com/boazsegev/combine_pdf/blob/f9b9f22a85458fac0f505b0eb6960e75f0742459/lib/combine_pdf/pdf_public.rb#L225-L250).

If all you need is to count the number of pages in a PDF, this might not be the optimal gem for your needs.

Kindly,
   Bo.

**Comment by curiosport** [comment]
@boazsegev  I don't really want to use any gem, many work the same as yours, they always apply functions I don't need, but then do you know any way to count the pages with pure Ruby?

**Comment by boazsegev** [comment]
I'm sorry, I can't think of any way to do so without parsing the PDF (at least partially, if not fully).

**Comment by curiosport** [comment]
Thanks anyway, I read that I could create a virtual printer and every page that is "printed" counting it, is a good idea but with Ruby there are no examples of how to do it.

**Comment by boazsegev** [comment]
I think a virtual printer would cost more (in performance) than using a gem in order to parse the PDF and count the pages.

I'm not sure why you don't want to use any gems in your project, but I think gems are an important resource. Yes, dependencies should be kept to a minimum where possible, but parsing a PDF file is probably not something you want to code from zero.
