### ISSUE TITLE
PDF blank when parse

### ISSUE THREAD

**Issue by btrd** [boazsegev/combine_pdf#166]
First of all thanks for your gem, super useful.

I have a strange bug, when I parse a document then save it, the content is only blank pages. I have the right count of pages but no content.

```ruby
content = File.open('original.pdf').read
parse = CombinePDF.parse(content).to_pdf.force_encoding('UTF-8')
File.new('test.pdf', "w").write(parse)
```

Can I send you the document via email ?

Thanks !

**Comment by boazsegev** [comment]
@btrd  You're welcome :)

Please send me the PDF by email and I'll see what I can do.

P.S.

Make sure to use binary read / write operations with PDF files.

You could use the [`#save` method](https://www.rubydoc.info/gems/combine_pdf/1.0.16/CombinePDF/PDF#save-instance_method) which does the same thing using `IO#binwrite`:

```ruby
content = File.open('original.pdf').read
content.save('test.pdf')
```

**Comment by cschilbe** [comment]
I am also experiencing this issue. I have noticed that the `CombinePDF.parse` step is ending up blank even though I can see there is correct data in the incoming PDF.

The resulting combined PDF then contains blank pages.

I know that some information is parsed as the combined pages are of the same size as the parsed pages.

Any work-around would be greatly appreciated

**Comment by boazsegev** [comment]
@cschilbe ,

Thank you for joining the conversation.

If you could post or email me a PDF that allows me to recreate the issue, it might help.

However, please note: Just because a PDF viewer will **display** a PDF file does **not** mean the PDF file isn't **corrupted**.

PDF viewers **auto-correct** many PDF issues, sometimes using a "best guess" approach. CombinePDF does not attempt to correct anything that isn't a straightforward issue (mostly for performance reasons, but also under the assumption that the PDF files fed to CombinePDF can be fixed **before** being used with the gem).

**Try this: open the PDF in a PDF viewer and export / print the PDF as a new PDF file. Try using the resulting (new) PDF file with CombinePDF (in the same code where you had issues)**.

**If the issue doesn't persist, it's likely that the original PDF was malformed in some way**.

Thanks again for joining the conversation.

Kindly,
   Bo.

**Comment by boazsegev** [comment]
Hi @cschilbe ,

Thank you for the email 🙏🏻🙏🏻🙏🏻

The extra information helped me track down the issue and squash a bug 👏🏻👏🏻👍🏻

It seems that the example PDF you provided contained nested data that was falsely marked as a duplicate. This was a CombinePDF bug that was hidden away by the fact that most PDF authoring tools avoid deeper nesting structures.

I tried to patch the issue with CombinePDF 1.0.17 - can you test that this works for you?

Kindly,
   Bo.

**Comment by cschilbe** [comment]
That’s awesome! I will test early tomorrow!

**Comment by cschilbe** [comment]
Bo - the latest version works! Thanks for the quick resolution!

**Comment by btrd** [comment]
Thanks, both of you! Sorry I completely forgot this issue.
