### ISSUE TITLE
How to avoid garbled characters pdf title when I see the pdf in chrome browser?

### ISSUE THREAD

**Issue by iToshk** [boazsegev/combine_pdf#192]
I set a Japanese title via conbine_pdf like
`pdf.info[:Title] = "てすとdayoアイウエオ"`
However, in the browser, it shows like this.
-> ã†¦ã†Žã†¨dayoã‡¢ã‡¤ã‡¦ã‡¨ã‡ª
Is there any way to avoid this?
<img width="237" alt="スクリーンショット 2021-03-23 21 04 13" src="https://user-images.githubusercontent.com/8890795/113565712-6a495500-9646-11eb-8ee2-6ec1ea39037f.png">

**Comment by boazsegev** [comment]
Hi @iToshk ,

The PDF standard doesn't support UTF-8. Multi-lingual documents are handled by using Fong mappings where ANSI letters are mapped to the international glyph.

However, the title information has no font and no mapping, so I think it's restricted to ANSI letters...

... at least, this was the case before PDF 2.0. I have no idea how the new standard looks because it isn't available for free.

I have no idea how to change that.

Kindly,
Boaz Segev.

**Comment by iToshk** [comment]
@boazsegev Thanks for the answer!!
After checking out your UTF-8 BOM suggestion (unfortunately, it didn't work :( ) I had been thinking about the way without inserting the title with any gems...
And I found a solution for that!
I'm using `send_data` method for sending data and I found that the method has a `url_based_filename: false` option.
I tried it and now the chrome browser is showing filename! ;)

Best,
iToshk

**Comment by iToshk** [comment]
Ah, sorry url_based_filename: false didn't fix it.
I used rubyXL gem for putting a title in the end.

My situation
```
I was dealing with PDF created from excel through libreconv. 
1) Modify excel title with rubyXL gem
↓
2) Convert it to pdf with libreconv gem (the pdf has title with non garbled characters)
The actual method in rubyXL is here. https://github.com/weshatheleopard/rubyXL/issues/395#issuecomment-818500049
```

It's just FYI.

**Comment by conorom** [comment]
I'm not sure what will happen with Chrome's reading of the title metadata but it might be worth [trying UTF-16 encoding](https://github.com/boazsegev/combine_pdf/issues/188#issuecomment-831377639) when setting it.
