### ISSUE TITLE
PDF 1.5 Object Stream Error when combining file created with Prawn

### ISSUE THREAD

**Issue by hamitron** [boazsegev/combine_pdf#22]
So I'm trying to watermark on demand in my rails app. I'm using using Prawn to generate the stamp across a blank page, and then Combine_Pdf to combine that with watermark with an existing pdf file.  The combine process has been successful so far, but I keep getting the warning "PDF 1.5 Object streams found - they are not fully supported! attempting to extract objects."

The watermarks from Prawn are only text objects, but is there anything I should do to avoid this warning message?

**Comment by boazsegev** [comment]
The "PDF 1.5 Object streams found - they are not fully supported! attempting to extract objects." warning is raised whenever you open a PDF file that utilizes Object Streams for compression (a feature introduced in PDF version 1.5 and used to compress the PDF data).

Decompression support is limited to the standard basic compression, so errors might occur if the PDF utilizes specialty compression algorithms for the compressed Object Streams (which is something I haven't encountered but is theoretically possible).

The log is there because silent errors might occur if the decompression fails and I feel uncomfortable removing the message.

Than again, decompression failure _should_ result in an exception rather than corrupt data, but I couldn't test that. If an exception is sure to be raised, the log message should probably be removed.

Having said that... the only solution I can think of, without changing the core code for CombinePDF, would be to use decompressed PDF files, without any Object Streams.

Please let me know if you think the logging scheme should be changed.

**Comment by tomascharad** [comment]
+1

**Comment by tomascharad** [comment]
Do you have any idea how could I decompress the PDF?

**Comment by tomascharad** [comment]
I'm receiving no implicit conversion of Symbol into Integer when ussing the '<<' operator.

**Comment by boazsegev** [comment]
Hi, thanks for bringing in the issue!

can you post some example code to reproduce the issue? mine seems to work.

As for decompression (inflation), CombinePDF automatically attempts to inflate the file when encountering a compressed data segment is it need to edit (or read) for content management. To add support for more compression algorithms, [look into the inflate implementation](https://github.com/boazsegev/combine_pdf/blob/dce7f2bb63365bdfcb10c21d1dcc56888af07f79/lib/combine_pdf/filter.rb#L36-L94).

**Comment by tomascharad** [comment]
The code is basically this:

    pdf = CombinePDF.load(file.path)
    ...#folios.pdf generation (Using prawn)...
    pdf_folios = CombinePDF.load "folios.pdf"
    pdf.pages(false).each_with_index do |page, index|
      new_page = pdf_folios.pages(false)[index]
      page << new_page
    end

Here is a link to the pdf: https://drive.google.com/open?id=0B3F-Rn6bPunbSVJfd3NmMlpTOU0

**Comment by boazsegev** [comment]
Hi Tomás,

I couldn't download the file just yet (waiting for a confirmation on my request to do so), just a quick question - are you sure the page numbers fit? could it be that your `folios.pdf` has less pages then the pdf loaded?

Try this:

```ruby
pdf = CombinePDF.load(file.path)
...#folios.pdf generation (Using prawn)...
pdf_folios = CombinePDF.load "folios.pdf"
pdf.pages.each_with_index do |page, index|
  new_page = pdf_folios.pages[index]
  raise "I'm out of data" if new_page.nil?
  page << new_page
end
```

If you have just two stamp pages (it's very common to have a cover page logo and a small logo on every normal page), you can try:

```ruby
pdf = CombinePDF.load(file.path)
...#folios.pdf generation (Using prawn)...
pdf_folios = CombinePDF.load "folios.pdf"
stamp = nil
pdf.pages.each do |page|
  page << (stamp || pdf_folios.pages[0])
  stamp ||= pdf_folios.pages[1]
end
```

**Comment by tomascharad** [comment]
Were you able to check the pdf that I sent you?

**Comment by boazsegev** [comment]
Yap, and I confirm there's an issue with the resource merger... I'm working on it.

**Comment by boazsegev** [comment]
Damn... I resolved the issue, but hit a different one - now the stamping fails (I get blank pages)... this might take a while...

**Comment by tomascharad** [comment]
Ok no worries! Thank you very much!

**Comment by boazsegev** [comment]
Hi Tomás,

I just released a fix in version 0.2.15 and it works on my system... Could you check that it works for you and check if any issues pop up?

Please let me know how it works,
   Bo.

**Comment by tomascharad** [comment]
Hi Bo,

I just checked and seems to work fine!
Many thanks! May I know why the pdf had problems? Is a new version or something?

**Comment by boazsegev** [comment]
Hi Tomás,

Thanks for the update, I'm happy we caught this one.

As to why this specific PDF experienced the issue - the PDF's page content stream reference was unexpectedly nested inside a reference object with no dictionary... a short translation is this:

PDF data is mostly in Dictionaries, and they can share values by using object pointers instead of data. All of these are mapped to Ruby Hash objects.

A page's content is usually an array of pointers to the actual content streams (allowing for a number of streams per page)...

...but in this case the content was a pointer to an array of pointers (which is totally fine with the standard, but it doesn't make sense, since this array is expected to be unique for each page and using pointers here would just waste space in the file).

Anyway, CombinePDF wasn't prepared for this contingency and it resulted in the Array being used where a Hash (dictionary) was expected and the Hash (dictionary) being used where the Array was expected.

I added more validations for this possible pointer nesting.

**Comment by tomascharad** [comment]
Bo,

Thank you very much for your work and explanation.
It has been a pleasure to work with your Gem.
If you need any help with something just let me know.

**Comment by tomascharad** [comment]
Just to add more context to further readers, the scanner is an HP Scanjet Enterprise Flow 7500

**Comment by matisoffn** [comment]
@boazsegev I'm having the same issue.  I'm combing about 8 PDFs into one, and losing the form fields in my documents once it's combined.

What can I do to fix this?

**Comment by boazsegev** [comment]
Hi Noah Matisoff,

Thank you for posing this update.

PDF form data is stored in global objects (not attached to the specific PDF page) and loss of data may occur.

I just released an updated version that should preserve the form data when you combine whole PDF files together, but conflicts may occur (i.e. form fields with the same name might cause data to be overwritten or corrupt the form data).

I also updated the README to point out this issue (the issue also exists with certain links and other special PDF objects).

I hope this fixes your issue.
