### ISSUE TITLE
Combined doc starting with a top margin

### ISSUE THREAD

**Issue by cw6365** [boazsegev/combine_pdf#25]
I am writing to one file and then combining with another, the blank file i write on has the correct co-ordinates and writes in the correct place, but when combined with the original file a top margin seems to be added, see screenshot below. 

![screen shot 2015-08-07 at 14 20 56](https://cloud.githubusercontent.com/assets/665123/9136668/726088de-3d10-11e5-838e-e8aa96d2d505.png)

Can i remove the top margin when combining? or any ideas why this happens?

**Comment by boazsegev** [comment]
This probably happens because you are using two different page sizes, so that the coordination system changes according to the page size.

In PDF, the coordination system starts at the bottom left corner, so the top margin is probably caused by a higher page.

There are two options I can see:

1. You can resize the pages of the second file (although you probably wanted that page size).

2. You can first copy the size of the second file and use that size when creating the pages for the first file.

3. You can directly write to a copy of the second file (this seems like the best solution to me).

If you attach your code, maybe we can try one of these solutions together.

It would be something to this effect:

```ruby
file2 = CombinePDF.load path
page_size = file2.pages[0].page_size

# when creating a new page:
file1 = CombinePDF.new
page =  file1.new_page(page_size)

# write your data
page.textbox 'hello'
```

Please let me know if this solves the issue.

**Comment by cw6365** [comment]
Issue solved thanks. You was right about the different sizes. We used option 2) to get the dimensions and use them to generate a new prawn doc. The combine then worked perfect. Thanks for taking your time out to answer the question comprehensively.

**Comment by cw6365** [comment]
I'm slightly off in Prawn as the numbers come back rounded and prawn expects either the correct floats or the symbol, eg A4, is there anyway to get this accuracy please?

A4	
> 595.28 x 841.89

**Comment by boazsegev** [comment]
Can you post the code that gives you rounded numbers?

I tested some code on my machine and it keeps the float data in the page size.

Here the code for a new PDF with A4 dimensions:

```ruby
pdf = CombinePDF.new
pdf.new_page([0, 0, 595.28, 841.89]).textbox "Hello!"
pdf.save 'demo-A4.pdf'
pdf.pages[0].page_size # => [0, 0, 595.28, 841.89]
pdf = CombinePDF.load 'demo-A4.pdf'
pdf.pages[0].page_size # => [0, 0, 595.28, 841.89]
```

As you can see, I can create, save and load exact floats in the page's size (PDF's don't have to start the coordination system at 0,0 - this is why we set the first two numbers as 0,0)...

The same goes for the logos you gave me:

```ruby

logo1 = CombinePDF.load("watermark_1st_page.pdf").pages[0]
logo2 = CombinePDF.load("watermark_other_page.pdf").pages[0]

logo1.page_size # => [0, 0, 595.2, 841.92]
logo2.page_size # => [0, 0, 595.2, 841.92]
```

**Comment by cw6365** [comment]
Maybe it is my document

    143:   def dynamic_fields(pdf_path, fields, signer)
    144:
    145:     #Generate a blank PDF...
    146:     text_path = pdf_path.gsub('doc', 'text')
    147:     page_size = CombinePDF.load pdf_path
    148:     binding.pry
    149:     begin
    150:       Prawn::Document.generate(text_path,
    151:                                 :page_size => [page_size.pages[0].page_size[2], page_size.pages[0].page_size[3]],
    152:                                 :margin => 0) do
    153:         pdf_dimensions = [bounds.width, bounds.height]

[1] pry(#<PdfTasks>)> page_size.pages[0].page_size
=> [0, 0, 595, 842]
[2] pry(#<PdfTasks>)>

**Comment by cw6365** [comment]
I get the same with this random pdf found online too

http://spie.org/Documents%2FPublications%2FProcSampleManuscript-A4.pdf

[1] pry(#<Prawn::Document>)> load_pdf.pages[0].page_size
=> [0, 0, 595, 842]

**Comment by boazsegev** [comment]
You do raise a good point that I should write a resize method that accepts a new page size and stretches or shrinks the existing page to fit the new size... but this might have to wait...

_As for your specific case_:

The random file you found on line really has the page size `[0, 0, 595, 842]`... no floats there.

The [standard paper size listed here](http://www.prepressure.com/library/paper-size) for A4 is also 595, 842 points...

Also, if I go to this [PDF resizing page](https://docupub.com/pdfresize/), it values A4 at  `[0, 0, 595, 842]`.

Maybe Prawn is the one rounding up the numbers to get you to match the standard...?

In fact, I would consider fixing the Logo PDF files... it seems maybe they should have the size  `[0, 0, 595, 842]` instead of `[0, 0, 595.2, 841.92]`...?

**Comment by boazsegev** [comment]
I added a resize method for each page, so you can dynamically resize the page copied to match your target...

Please upgrade to version 0.2.4 to use this new method.

demo code:

```ruby
pdf = CombinePDF.load 'file.pdf'
logo_page = CombinePDF.load('file.pdf').pages[0]

pdf.pages.each {|p|  p << logo_page.copy.resize( p.page_size ) }
```

**Comment by cw6365** [comment]
Great thanks
