### ISSUE TITLE
PDF page stamping and text writing might fail when the resources dictionary contains reference (indirect) objects

### ISSUE THREAD

**Issue by sega** [boazsegev/combine_pdf#37]
I am trying to add the first page of one pdf file as background of every page of another pdf file. This works fine for most normal files but I have found some files which won't work. You can find one example at https://www.dropbox.com/s/p0m6fd59st42kkd/bg_ftc.pdf?dl=0
The file was created with word afaik (sorry for that).

You can reproduce my problem with the following minmal example:

```
b = CombinePDF.load("bg_ftc.pdf").pages[0].copy(true)
o = CombinePDF.new
o << [b]
o.save "o.pdf"
```

**Comment by boazsegev** [comment]
Hi Sega,

Thank you very much for posting the issue and helping improve the combine_pdf library.

I tracked down one issue related to the file you sent. The PDF itself is malformed.

The PDF standard states that:

> There should be an end-of-line marker after the data and before endstream;

But the PDF file you sent me does not follow the standard.

I will work on a fix, hoping that conforming PDF files don't get abused (as they could, potentially, contain the `endstream` keyword in the middle of the stream when not prefixed by an EOL).

I'm not sure if this is the source of the issue, but it is disrupting the correct flow (i.e., causing the `endstream` to appear twice)...

I'll keep you posted as I research the issue some more.

Bo.

**Comment by boazsegev** [comment]
Quick status update.

I'm using the following code for testing the different possible uses - reading and saving the PDF, combining the PDF into another and using the PDF as a stump:

```ruby
pdf = CombinePDF.load "bg_ftc.pdf"
n = CombinePDF.new
n.new_page.textbox "Hello!!!", font: :Courier
pdf.save '1_o.pdf'
n.save '1_n.pdf'
n << pdf
n.save '2_c_pdf.pdf'
n = CombinePDF.new
n.new_page.textbox "Hello!!!"
n << pdf.pages
n.save '2_c_array.pdf'
n = CombinePDF.new
n.new_page.textbox "Hello!!!"
n << [pdf.pages[0]]
n.save '2_c_array_1.pdf'
n = CombinePDF.new
n.new_page.textbox "Hello!!!", font: :Courier
n.stamp_pages pdf.pages[0]
n.save '3_s_stump.pdf'
n = CombinePDF.new
n.new_page.textbox "Hello!!!", font: :Courier
n.pages[0] >> pdf.pages[0]
n.save '3_s_back.pdf'
n = CombinePDF.new
n.new_page.textbox "Hello!!!"
n.pages[0] << pdf.pages[0]
n.save '3_s_front.pdf'
```

Everything seems to work (no errors are shown), BUT:

* stumping doesn't display correctly on Preview (does seem to display correctly on Acrobat Reader).

* Textbook font sizes for Helvetica (default font) seem off, but I'm not certain... it could be a mediabox page attribute being adjusted... but I think they're off. Seems they are effected by the resize property applied to the `bg_ftc.pdf` content stream (for some reason, PrimoPDF (the original PDF producer) shrinks all the data from 100% to 80%).

Resolving the `endstream` keyword issue did not resolve the compatibility issue with PrimoPDF.

**Comment by boazsegev** [comment]
Hi Sega,

I found the issue 😎

Thank you very much for pointing it out, as indeed this was an issue with the combine_pdf library 👍🏻

During a `stamp` operation, the CombinePDF library did not copy the page resources correctly when one of the resource directory key-value pairs was a referencing an external object.

The CombinePDF library was able to manage only one level of referencing. Now it is able to reference two levels of referencing (which should be all that is needed) when merging page's resources during a stamp operation.

I'm running a few more tests, but should be releasing version 0.2.13 with a patch in a few minutes.

**Comment by boazsegev** [comment]
released version 0.2.13, issue resolved on my system.

Sega, could you confirm that the patch works on your setup?

**Comment by sega** [comment]
Hi Bo, 

thank you very much for your quick response. I've done some testing and am still having issues with this file. I am using the aforementioned background file and try to use it for stamping with the following foreground file: https://www.dropbox.com/s/jqyrj8hgtt2uh0j/fg.pdf?dl=0

When I run
```
b = CombinePDF.load("bg_ftc.pdf").pages[0]
f = CombinePDF.load("fg.pdf")
o2 = CombinePDF.new; f.pages.each{|p| o2 << [p << b.copy(true)]}; o2.save "o2.pdf"
o3 = CombinePDF.new; f.pages.each{|p| o3 << [b.copy(true) << p]}; o3.save "o3.pdf"
```

both files (o2.pdf and o3.pdf) are not correct. The receiver address is hidden by a white (text?) box (which i try to work around by creating a new file and then adding and stamping the pages one by one).

Thank you for your work :-)

Cheers

sega

**Comment by boazsegev** [comment]
Testing your code I can see the unwanted result.

The result happens because the "background" PDF has a big white box (it's part of the file's content) and it's rendered over the "foreground" PDF instead of the other way around.

The following code works for me... but I also different backgrounds for each page (I use the second page as the background for all the pages except the first one:

```ruby
b = CombinePDF.load("bg_ftc.pdf").pages
f = CombinePDF.load("fg.pdf")

f.pages.tap do |pages|
   pages.each_index do |i|
       pages[i] >> b[ [1,i].min  ]
   end
end

# # I had it as a one-line in the irb terminal, like this:
# f.pages.tap {|ps| ps.each_index {|i| ps[i] >> b[ [1,i].min  ]} }

f.save 'out.pdf'
```

Notice that I'm using the `>>` operator and not the `<<` operator, to add background and not stamp over.

P.S.

* There is no need to create an Array when pushing a page into the new PDF (`o2 << [p << b.copy(true)] `). This would work: `o2 << (p >> b)`. 

* The `copy(true)` is now automated, you don't need to write it. CombinePDF will automatically attempt to recognize possible resource conflicts and it will use either copy(true) or copy(false) according to the actual data.

The working code would look like this:

```ruby
o2 = CombinePDF.new; f.pages.each{|p| o2 << (p >> b)}; o2.save "o2.pdf"
```

**Comment by sega** [comment]
Thank you once again. The result looks exactly as I want it. I have a bunch of pdf-files for further testing and will report if everything works out fine.

**Comment by sega** [comment]
I tested with some other files and

**Comment by boazsegev** [comment]
Thank's for the feedback and good luck!

P.S.

1. Data extraction from optional content files isn't supported just yet. I'm sorry for that. I tried getting into that a while back but the data structure did not allow me to know how which data is valid and which isn't after a page was extracted from the file... I hope to resolve this in the future, but I doubt I'll get to it any time soon unless someone helps with a pull request.

2. Some warnings are normal. For instance, PDF's "NULL" object can be either a NULL reference or a real reference to an object that wasn't initialized... CombinePDF can't tell of the uninitialized object's content wasn't found due to an issue with the parser or because it was a NULL reference. This would result in a warning.
