### ISSUE TITLE
CombinePDF.parse fail when PDF has comments with some special string.

### ISSUE THREAD

**Issue by lgn21st** [boazsegev/combine_pdf#39]
Hello,

First of all, I'd like to thank you for you to provide this great PDF merge tool.

My client use some tools to generate PDF and turn out it will insert some random comments into the PDF file, here is a example:

```
5 0 obj
% [8496] 
<<
/Filter /FlateDecode
/Length 3739
>>
stream
...
endstream
endobj
```

the line NO.2 will cause Runtime Error with message "Unknown PDF parsing error - maleformed PDF file?", my temporary solution is just ignore all comments but I'm not sure if I break something else, please advise, thanks again.

https://github.com/lgn21st/combine_pdf/commit/a0cc17ec349fd1d8469d07e5ad2dce37d5062b5f

**Comment by boazsegev** [comment]
Hi Daniel,

Thank you very much for your interest in CombinePDF and for bringing this issue to my attention.

The update you considered will break some compatibility consideration with other (less conforming) PDF writers. Some PDF writers forget to add an EOL marker and put PDF information in the comment line...

Can you send me an example file, so that I could work on testing and resolving the issue?

Thanks!
Bo.

**Comment by lgn21st** [comment]
@boazsegev Thank you for your attention, here is the link of the sample file:

https://www.dropbox.com/s/2d2q073jfydapzr/sample.pdf?dl=0

**Comment by boazsegev** [comment]
Hi Daniel.

I tested the fix on my machine and it works for me.

Could you update to version 0.2.14 and check that this fix also works for you?

Again, thank you for pointing out the issue and directing my attention to it's cause.

Best regards,
 Bo (Boaz Segev).

**Comment by lgn21st** [comment]
Hi @boazsegev 

:+1: :+1: :+1: 

I just tested it in my environment and it work perfect, thank you for your quick fix and very responsible!

Best regards,
Daniel.

**Comment by boazsegev** [comment]
Thank you, Daniel. 🙏🏻

**Comment by rickbyington** [comment]
Fixed our issue as well. Thanks!
