### ISSUE TITLE
undefined method errors after 0.2.18 update

### ISSUE THREAD

**Issue by LeptonHeavy** [boazsegev/combine_pdf#56]
have script that combines latest version of a PDF from several folders in a hierarchy - combining them into a single PDF.

Under 0.2.17 it works as expected - under 0.2.18 I get an error when adding the second pdf to the new document.
error:
```
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/combine_pdf-0.2.18/lib/combine_pdf/pdf_public.rb:303:in `insert': undefined method `update' for nil:NilClass (NoMethodError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/combine_pdf-0.2.18/lib/combine_pdf/pdf_public.rb:275:in `<<'
        from C:/Users/User02/Documents/combinePDF/combine.rb:62:in `block in <main>'
        from C:/Users/User02/Documents/combinePDF/combine.rb:57:in `each'
        from C:/Users/User02/Documents/combinePDF/combine.rb:57:in `<main>'
```
ruby code
```
# file_list is an array of PDF files - something like:
# ["R:/Project DS/C/A1_3_151203_Construction.pdf", "R:/Project DS/B/A1_2_160410_Permit_Revisions.pdf","R:/Project DS/C/A1_3_160412_More_Permit_Revisions.pdf"]

pdf_merge = CombinePDF.new
file_list.each do |pdf_file|
  pdf_merge << CombinePDF.load(pdf_file)	
end
```

**Comment by boazsegev** [comment]
Hi @LeptonHeavy,

Thank you so much for pointing this out 👍 👍 👍 

I uploaded a patched version to github. Could you check that this resolves the issue?

Thanks,
   Bo.

**Comment by EmberSher** [comment]
I'm kind of new to github, so I'm still getting used to the functions of these comments.

I'm still having this same problem.  Here's the error again:

`C:/Ruby21/lib/ruby/gems/2.1.0/gems/combine_pdf-0.2.18/lib/combine_pdf/pdf_public.rb:303:in 'insert': undefined method 'update' for nil:NilClass (NoMethodError)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/combine_pdf-0.2.18/lib/combine_pdf/pdf_public.rb:275:in '<<'
        from addinfo.rb:23:in '<main>'`


My code is straight out of the combine_pdf.rb, and looks like this:
`pdf = CombinePDF.new
pdf << CombinePDF.load("file1.pdf")
pdf << CombinePDF.load("file2.pdf")
pdf.save "combined.pdf"`

Since I'm new to github, I might simply not have the patch.  I re-downloaded the zip, thinking that might solve the issue, but unfortunately it didn't.  I'd love to use this gem for a project I'm working on for a class, though!

**Comment by boazsegev** [comment]
After downloading the `zip`, you need to copy (and overwrite) the `pdf_public.rb` file to the `C:/Ruby21/lib/ruby/gems/2.1.0/gems/combine_pdf-0.2.18/lib/combine_pdf` folder (the gem's folder).

After you overwrite this, you should have the patch.

The error might be resolved... of the error might move to a different line.

This week is finals at my collage, so I didn't get around to testing and releasing the patch. I'm not sure why the issue didn't come up with any of my `pdf` files when I was testing the 0.2.18 version.

**Comment by boazsegev** [comment]
I released a fixed version (v.0.2.20) - please check that this actually fixes the issue for you.

**Comment by EmberSher** [comment]
Alrighty!  Thanks!

**Comment by EmberSher** [comment]
It worked!  Thank you!

**Comment by boazsegev** [comment]
@EmberSher,

Thanks for letting me know and for reporting this issue and your experience.

@LeptonHeavy thanks again. Let me know if you have any issues, I'm closing this one for now.

**Comment by LeptonHeavy** [comment]
confirming that 0.2.20 works for me as well!
thanks for the speedy fix!

**Comment by boazsegev** [comment]
@LeptonHeavy , thanks for keeping me posted 👍
