### ISSUE TITLE
TypeError: no implicit conversion of Fixnum into Hash

### ISSUE THREAD

**Issue by kevshin2** [boazsegev/combine_pdf#69]
Hey Bo,

When I try to merge 2 PDF (The file that was splited in issue #66), I'm getting "TypeError: no implicit conversion of Fixnum into Hash", please see testing files in your email.

For file that do merge, after saving it, the file could not be opened.

Thanks

**Comment by boazsegev** [comment]
Hi Kevin, thank you for opening this issue.

I'm getting a similar result (an un-usable PDF file), but no errors... could you please provide the backtrace for the exception you got? It might provide a hint.

Thanks!
Bo.

**Comment by kevshin2** [comment]
Hey Bo,

Here is the backtrace.
lib/combine_pdf/pdf_protected.rb:240:in `merge'
lib/combine_pdf/pdf_protected.rb:240:in `hash_merge_new_no_page'
lib/combine_pdf/pdf_public.rb:300:in `update'
lib/combine_pdf/pdf_public.rb:300:in `insert'
lib/combine_pdf/pdf_public.rb:273:in `<<'

Thanks!

**Comment by kevshin2** [comment]
Hey Bo,

Just discover something interesting. For file that does merge, if you try to save the file for the first time, it will generate an un-usable PDF, but if you try to save it again, it will work.

Thanks,
Kevin

**Comment by kevshin2** [comment]
The error will occur when I'm trying to load a file from a url, and save it into a temp file.
temp_file = open(url)
pdf << CombinePDF.load(temp_file.path)
pdf << CombinePDF.load(temp_file.path) (error: no implicit conversion of Fixnum into Hash)

**Comment by boazsegev** [comment]
As for loading files from a URL, try using `parse`, since `open` will return a string, not a file. `load` takes a string and attempts to load the file from the local storage (using [`IO.binread`](http://ruby-doc.org/core-2.3.1/IO.html#method-c-binread)). If reading the file fails, `load` will try to recuperate... but parse is preferable.

Also, make sure the returned string (from the `open(url)` call) is valid and doesn't contain HTTP artifacts. I've seen PDF files being received with HTTP header data attached....

As to the issue - damn, it's a tricky one. I found the issue (in a general sense, a specific referenced object has it's Hash data corrupted, causing the reference to fail and print invalid data)... but I can't fine where it happens. Hopefully it won't be long.

**Comment by boazsegev** [comment]
Found it :-)

I can have a terrible patch in a really short while... or I can rewrite the name dictionary renaming algorithm without recursion, which is something on the to do list... well, I guess I'll try the long way and see how it goes.

**Comment by boazsegev** [comment]
I released an update - rewrote the name conflict resolution... we now have better support for links in PDF files :-)

I'm off to bed, but please let me know if this resolves your issue.

Since this is a double issue (also the one with relation to the parser failing), please let me know if using `CombinePDF.parse` instead of `load` helped at all (or maybe even provided more error information.

**Comment by kevshin2** [comment]
Hey Bo,

Thanks so much for the update. I did some testing with the new release, and the issues seems to be resolved. I will try it on a few more files, and definitely will let you know if there is any unresolved issues. As for the parsing, load seems to be working fine now, and I'm not seeing any issues related to "no implicit conversion of Fixnum into Hash" on files from a link.

Many thanks! :)
Kevin

**Comment by boazsegev** [comment]
Thanks for keeping me posted 👍 

As for using `parse` instead of `load`, `parse` should be faster (`load` will catch an exception and correct itself, but `parse` will not experience an exception).

I guess the  "no implicit conversion of Fixnum into Hash" was related to the same issue... although I think I will need to look into the hash update algorithm next and clean it up.

**Comment by kevshin2** [comment]
Currently load works fine. I was trying to test with parse, and I'm seeing some exception, maybe I'm not doing it correctly.

temp_file = open(url)

CombinePDF.load(temp_file.path) "works great"

CombinePDF.parse(temp_file.path) " RuntimeError Exception: Unknown PDF parsing error - maleformed PDF file?"

CombinePDF.parse(temp_file) "TypeError Exception: couldn't parse and data, expecting type String"

**Comment by boazsegev** [comment]
Oh, you're actually saving to a temp_file? my bad...

Have a look at the question in #62 

I was thinking `open(url).read` in my head... Sorry.

**Comment by kevshin2** [comment]
ah I see, would it be better to do it that way?

Thanks!

**Comment by boazsegev** [comment]
I think it would be faster.

**Comment by kevshin2** [comment]
The reason I decided to use a tempfile is open(url) is actually creating a temp file and assume it will clean up the file at some point later (correct me if I'm wrong). So I'm saving it as a tempfile and call tempfile.unlink after I'm done with the file. Any thoughts?

temp_file = open(url)
pdf << CombinePDF.load(temp_file.path)
temp_file.unlink

**Comment by boazsegev** [comment]
Since you're using the OpenURI extension, you will be limited to their constraints.

I have no idea what's the underlying implementation, so I'm not sure my advice helps...

I recommend you avoid OpenURI and use the Net::HTTP instead.

See this StackOverflow question for details <http://stackoverflow.com/a/30343104/4025095>.

http://stackoverflow.com/a/30343104/4025095

**Comment by boazsegev** [comment]
Since you're using the OpenURI extension, you will be limited to their constraints.

I have no idea what's the underlying implementation, so I'm not sure my advice helps...

I recommend you avoid OpenURI and use the Net::HTTP instead.

See [this StackOverflow question for details](http://stackoverflow.com/a/30343104/4025095).

**Comment by kevshin2** [comment]
Awesome, I will take a look, thanks again!
