### ISSUE TITLE
Several versions yanked?

### ISSUE THREAD

**Issue by sbleon** [boazsegev/combine_pdf#75]
First of all, thank you for the handy gem! It's very useful in one of my projects and very easy to use :-)

I was just wondering why so many versions have been yanked from rubygems.org. I think that gems should only be yanked if they accidentally include sensitive information that must not be published. Buggy versions should be left on rubygems because people may rely on that version, bugs and all.

**Comment by ivansifrim** [comment]
I'm also using 2.23 - could you please add it again?

**Comment by boazsegev** [comment]
In general I agree (see my comment on issue #74 ). However, in the last week I've been working very hard on improving some of the core algorithms that structure the PDF data in Ruby land and I inadvertently introduced new issues that didn't exist before, so that some PDF files that were correctly read on version 0.2.22 were suddenly throwing exceptions.

These issue were introduced because the test files I had at the time didn't encompass some PDF variants I wasn't aware of.

Now that the whirlwind had passed (and I have a few band new PDF files I can test against), CombinePDF is back to being as stable as version 0.2.22, meaning that any PDF file that version 0.2.22 was able to parse, version 0.2.27 is able to parse (actually, version 0.2.27 can do more).

I thought that by posting fast fixes to these issues I was doing enough. It was always possible to roll-back to older versions and be a late adopter, or be an edge user and get the latest fix.

However, issue #74 made me rethink this and I took the advice I was given and yanked the group of gems that introduced poorer performance then the 0.2.22 release.

As fo "un-yanking" version 0.2.23 (which I'm not sure if it was that last in the pre-revolution or the first in the engine revolution), I'm not sure I know how. If you know how, please let me know. If not, I would recommend version 0.2.27 which was tested against a larger group of PDF files and supports more PDF properties.

I am very sorry for any inconvenience. I'm doing my best, but sometimes I make mistakes... probably most of the time I make mistakes...

**Comment by ivansifrim** [comment]
No problem, thanks for making it and the quick response!

**Comment by sbleon** [comment]
@boazsegev, thanks for the detailed explanation! My preference is for less yanking, because every yank introduces the possibility that someone's build/deploy will be broken. I think it's OK to tell your users "please upgrade to latest", and that should generally be everyone's first resort when encountering a bug.

It's ultimately up to you as the maintainer which revisions get yanked, and you need to do whatever makes your life easier. Thanks again for the great gem!
