### ISSUE TITLE
Problem PDF results in error - any way to handle this more gracefully?

### ISSUE THREAD

**Issue by robvitaro** [boazsegev/combine_pdf#78]
undefined method `[]' for nil:NilClass

I'm new to Ruby and Rails, so I couldn't wrap my head around this one. In the end I am just performing my own rescue, but thought you would like to see this to find out if the gem could handle it better than I did.

[unsupported.pdf](https://github.com/boazsegev/combine_pdf/files/384480/unsupported.pdf)

**Comment by boazsegev** [comment]
Hi @robvitaro  and thank you very much for opening this issue.

I wanted to thank you for the file, as it helped me test the issue.

I'm still trying to figure out where things fall apart, however, from an initial inspection, I thought I should let you know that the file is **not** really valid (I doubt that this is why CombinePDF fails to open it).

The PDF file you sent me starts with what seems to be an XML meta tag:

```
<META NAME="ROBOTS" CONTENT="NONE"> 
%PDF-1.6
%...
```

This line is invalid. The PDF file should start with the `%PDF-1.6` version marker followed by a comment line (arbitrary data preceded by the `%` sign, indicating if the file is text encoded of binary encoded).

Ideally, I would be happier if CombinePDF managed to skip the invalid first line and read the PDF... It **should** do that, so I think the issue is somewhere else and I'll keep digging.

I'm mostly dropping this note to keep you posted and so you'd know I'm checking this issue out.

Again, thank you for opening the issue.
Bo.

**Comment by boazsegev** [comment]
I released a patch (It was the invalid string at the beginning of the file that made the parser fall into shambles)...

The parser a little better now, thanks to your decision to open this issue. Thank you.

As for having a rescue handler when parsing incoming foreign content - I think it is inevitable.

We cannot control what data is fed to our application. Not only through malicious (or curious) minds attempting to bring our applications to their knees, but also through user errors, robots / crawlers and other internet/jungle inhabitants.

The rescue should only handle errors, but error handling (and security) should always be part of a healthy network application's design.

Good luck on your RoR adventure (It's a lot of fun)!

Remember that Ruby is so much more then RoR and that you hardly need the framework to enjoy the language (it's quite amazing on it's own as well, sometimes even more so, since there's a thrill that comes from working close to the metal).

**Comment by robvitaro** [comment]
Wonderful news on the patch, and thanks for the encouragement. I had some help here at work to make an all purpose/generic rescue, so that was a good practice.

As for the pdf I sent you, I'll let our client know that they should probably regenerate it.

Again, thank you!
