### ISSUE TITLE
Force PDFs to scale to A4

### ISSUE THREAD

**Issue by aussiDavid** [boazsegev/combine_pdf#86]
When combing pdfs, is there a way to force the pdfs to scale or fit to a set size, such as A4?

**Comment by boazsegev** [comment]
Hi @aussiDavid ,

Sizes are a page specific property, not a PDF property.

You can find more information about obtaining a PDF page's size and resizing pages in the documentation, using methods such as [Page_methods#resize](http://www.rubydoc.info/gems/combine_pdf/0.2.31/CombinePDF/Page_Methods#resize-instance_method).

here's a quick conceptual demo (untested, I might have errors or spelling mistakes):

```ruby
pdf = CombinePDF.new
pdf << CombinePDF.load("file1.pdf") # one way to combine, very fast.
pdf << CombinePDF.load("file2.pdf")
pages = pdf.pages
first_page_size = pages[0].page_size
pages.each do |page|
  page.resize(first_page_size)
end
```

For future reference, programming questions are usually better posted in SO, so that more of the community can benefit from the answer as well as so that more people could answer you.

Openning a new issues is usually reserved for issues (bugs) and feature requests in the gem or it's  documentation.

**Comment by boazsegev** [comment]
P.S.

PDF page sizes can be found [here](https://www.prepressure.com/library/paper-size) using a simple google search.

To force A4, the same code could be used as:

PDF_A4SIZE = [0, 0, 595, 842]
pdf = CombinePDF.new
pdf << CombinePDF.load("file1.pdf") # one way to combine, very fast.
pdf << CombinePDF.load("file2.pdf")
pdf.pages.each do |page|
  page.resize PDF_A4SIZE
end

**Comment by aussiDavid** [comment]
@boazsegev  Thank you. I will keep to SO.

**Comment by boazsegev** [comment]
@aussiDavid , you're welcome :-)
